stty -ixon

HISTSIZE=
HISTFILESIZE=
HISTCONTROL=ignoredups

set enable-bracketed-paste on

alias diff="git diff --no-index"
alias grep="grep --color=auto"
alias vi="nvim"
alias vim="nvim"

export EDITOR="nvim"
export PAGER="page"
export MANPAGER="page -t man"

export PATH="/etc/nixos/bin:$PATH"
