user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("browser.download.always_ask_before_handling_new_types", true);
user_pref("browser.toolbars.bookmarks.visibility", "never");
user_pref("browser.uiCustomization.state", '{"placements":{"widget-overflow-fixed-list":[],"nav-bar":["back-button","forward-button","stop-reload-button","home-button","history-panelmenu","downloads-button","ublock0_raymondhill_net-browser-action","preferences-button","fxa-toolbar-menu-button","urlbar-container"],"toolbar-menubar":["menubar-items"],"TabsToolbar":["firefox-view-button","tabbrowser-tabs","new-tab-button","alltabs-button"],"PersonalToolbar":["personal-bookmarks"]},"currentVersion":18}');
user_pref("ui.key.menuAccessKeyFocuses", false);
user_pref("intl.locale.requested", "en-au,en-gb,en");
user_pref("font.default.x-western", "sans-serif");
user_pref("font.name.sans-serif.x-western", "Liberation Sans");
user_pref("font.name.serif.x-western", "Liberation Serif");
user_pref("font.name.monospace.x-western", "JetBrainsMonoNL Nerd Font Mono");
user_pref("font.size.monospace.x-western", 14);
user_pref("font.size.variable.x-western", 18);
user_pref("findbar.highlightAll", true);
user_pref("browser.aboutConfig.showWarning", false);
user_pref("browser.zoom.full", false);
